backend_ci: &backend_ci
  - '.github/workflows/backend*.yml'

backend:
  - *backend_ci
  - 'backend/**'


frontend_ci: &frontend_ci
  - '.github/workflows/frontend*.yml'

frontend:
  - *frontend_ci
  - 'frontend/**/*.ts'
  - 'frontend/**/*.tsx'
