# step 1: build go app
# 参考 https://qiita.com/sky0621/items/58fa2bcfc0935f6186cb
FROM golang:1.20.1-alpine3.17

ENV GOOGLE_APPLICATION_CREDENTIALS="/service_account/key.json"
ENV FIREBASE_AUTH_EMULATOR_HOST="192.22.0.3:9099"
ARG GCLOUD_PROJECT
ENV GCLOUD_PROJECT=${GCLOUD_PROJECT}

# for go mod download
RUN apk add --update --no-cache ca-certificates git bash curl
RUN mkdir /app
WORKDIR /app
COPY app/go.mod app/go.sum ./

RUN CGO_ENABLED=0 go install github.com/cosmtrek/air@latest
RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
RUN go mod download && go mod verify && go mod tidy
COPY app .
# hotreload
CMD ["air","-c",".air.toml"]
