version: "3.9"
services:
  web:
    container_name: go_app_remote
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - "8080:8080"
    depends_on:
      - "sql_proxy"
      - "firebase"
    command: /app/wait-for-cloudsql.sh air -c .air.toml
    volumes:
      - ./cloudsql:/cloudsql
      - ./app:/app
    env_file:
      - ./.env.remote
    networks:
      - remote_default
  # firebase emulator
  firebase:
    build:
      context: ./firebase
      dockerfile: ./Dockerfile
      args:
        - GCLOUD_PROJECT=${GCLOUD_PROJECT}
    container_name: firebase
    ports:
      - 4000:4000
      - 9099:9099
    # ip固定
    networks:
      remote_default:
        ipv4_address: 192.22.0.3
    tty: true
    volumes:
      - user-data:/opt/workspace/firebase
  sql_proxy:
    container_name: sql_proxy
    build:
      context: .
      dockerfile: ./cloudsql/Dockerfile
    restart: always
    volumes:
      - ./cloudsql:/cloudsql
      - ./service_account:/service_account
    networks:
      remote_default:
        ipv4_address: 192.22.0.5

volumes:
  data-volume-remote:
  user-data:
networks:
  remote_default:
    name: remote_default
    driver: bridge
    ipam:
      config:
        - subnet: 192.22.0.0/16
