version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    # mac対応
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql_host
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: go_fooder_dev
      MYSQL_DATABASE: fooder
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    # 永続化
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume:
