package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"backend/app/ent"
	"context"
	"fmt"
)

// RegisterStore is the resolver for the registerStore field.
func (r *mutationResolver) RegisterStore(ctx context.Context, id string, name string) (*ent.Store, error) {
	panic(fmt.Errorf("not implemented: RegisterStore - registerStore"))
}

// UpdateStore is the resolver for the updateStore field.
func (r *mutationResolver) UpdateStore(ctx context.Context, id string) (*ent.Store, error) {
	client := ent.FromContext(ctx)
	return client.Debug().Store.UpdateOneID(id).Save(ctx)
}

// GetStoreByID is the resolver for the getStoreById field.
func (r *queryResolver) GetStoreByID(ctx context.Context, id string) (*ent.Store, error) {
	client := ent.FromContext(ctx)
	return client.Debug().Store.Get(ctx, id)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) CreateStore(ctx context.Context, id string, name string) (*ent.Store, error) {
	client := ent.FromContext(ctx)
	return client.Debug().Store.Create().SetID(id).SetName(name).Save(ctx)
}
