name: Deploy
on:
  push:
    paths:
      - 'backend/app/**'
jobs:
  deploy:
    runs-on: ubuntu-latest


    permissions:
      contents: read
      id-token: 'write'

    steps:

      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: ci-user@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com

    # This example uses the docker login action
      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - run: echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: Docker Build
        run: |-
          cd backend
          docker build -t ${{ secrets.SERVICE_NAME }} -f ./dockerfile.prod  .
          docker tag ${{ secrets.SERVICE_NAME }} gcr.io/${{ secrets.GCP_PROJECT }}/${{secrets.SERVICE_NAME}}:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{secrets.SERVICE_NAME}}:latest

      - name: Deploy
        if: github.event_name == 'push'
        run: |-
          gcloud beta run deploy ${{ matrix.service }}
            --platform managed
            --region ${{ secrets.GCP_REGION }}
            --image ${{ steps.image-url.outputs.value }}
            --tag pr-${{ github.event.pull_request.number }}
            --no-traffic

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "Preview"

      - name: Create Preview URL
        id: preview-url
        run: echo "::set-output name=value::https://pr-${{ github.event.pull_request.number }}---product-x-drwvbiotlz-an.a.run.app"

      - name: Get datetime for now
        id: datetime
        run: echo "::set-output name=value::$(date)"
        env:
          TZ: Asia/Tokyo

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Visit the :eyes: **Preview** :eyes: for this PR (updated for commit ${{ github.event.pull_request.head.sha }}):
            <${{ steps.preview-url.outputs.value }}>
            <sub>(:fire: updated at ${{ steps.datetime.outputs.value }})</sub>
          edit-mode: replace
