name: build
on:
  pull_request:
    branches:
      - 'main'
env:
  GCP_PROJECT: ${{secrets.GCP_PROJECT}}
  GCP_PROJECT_NUM: ${{secrets.GCP_PROJECT_NUM}}
  SERVICE_NAME: ${{secrets.SERVICE_NAME}}
  REGION : ${{secrets.REGION }}
jobs:
  build:
    runs-on: ubuntu-latest


    permissions:
      contents: read
      id-token: 'write'

    steps:

      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: true
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/github-actions/providers/gha-provider
          service_account: ci-user@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com

      - id: 'gcloud'
        name: Authenticate
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud --quiet auth configure-docker

      - name: Docker Build
        run: |-
          docker build -t ${{ env.SERVICE_NAME }} -f ../backend/Dockerfile.prod  .
          docker tag ${{ env.SERVICE_NAME }} gcr.io/${{ env.GCP_PROJECT }}/${{env.SERVICE_NAME}}:latest
          docker push gcr.io/${{ env.GCP_PROJECT }}/${{env.SERVICE_NAME}}:latest
