name: Lint

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml
  lint:
    needs: changes
    if: steps.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get pkg.json
        id: package-json
        run: echo "content=$(cat ./package.json | tr -d '\n')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: ${{fromJson(steps.package-json.outputs.content).engines.node}}
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn lint
