name: Lint

on:
  push:
    paths:
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get pkg.json
        id: package-json
        run: echo "content=$(cat ./package.json | tr -d '\n')" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: ${{fromJson(steps.package-json.outputs.content).engines.node}}
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
