name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml

      - name: Get pkg.json
        id: package-json
        run: echo "content=$(cat ./frontend/package.json | tr -d '\n')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: ${{fromJson(steps.package-json.outputs.content).engines.node}}
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - if: steps.changes.outputs.frontend == 'true'
        run: yarn lint
